// packages/shared-ui — DESIGN LOCKED barrel export
export * from './tokens/colors'
export { Popover, PopoverTrigger, PopoverContent }       from './primitives/popover'
export { Tooltip, TooltipTrigger, TooltipContent }       from './primitives/tooltip'
export { EntityChip, ENTITY_TYPE_CONFIG, INTERNET_SEARCH_URLS } from './components/EntityChip'
export type { EntityType, Severity }                             from './components/EntityChip'
export { InvestigationPanel }                                    from './components/InvestigationPanel'
export { TopStatsBar }                                           from './components/TopStatsBar'
export { IntelCard }                                             from './components/IntelCard'
export { SeverityBadge, SeverityDot }                           from './components/SeverityBadge'
export { GlobalSearch, useGlobalSearch }                        from './components/GlobalSearch'
export { PageStatsBar, CompactStat }                            from './components/PageStatsBar'
export { TooltipHelp }    from './components/TooltipHelp'
export { InlineHelp }     from './components/InlineHelp'
export { SkeletonBlock }  from './components/SkeletonBlock'
